### ISSUE TITLE
Admin login

### ISSUE THREAD

**Issue by stsfaroz** [MarianoMolina/project_alice#7]
how to setup a admin role , couldnt find anything related to it

**Comment by MarianoMolina** [comment]
There is currently very little reason to create an Admin role. Its available in principle, but haven't added it to the normal flow because its kinda useless. Let me explain:
- Creating an account essentially creates an environment where you can work in isolation to other things. Its great if you have multiple people that want to use it, for example. 
- And admin role is mostly about having full access to the database according to the Backend. Meaning: if you ask the backend for an entity id owned by another user as an Admin, you will receive it. The idea with this was to be able to do cross-user data analysis at some point, to enable cost tracking and shared API keys. 

Now, unless you have several users and want to be able to track their usage, its not really all that useful to create an Admin user at the moment. I literally haven't done it myself yet =) But its coming! 

With all that said, its an issue that this noise (useless admin role) exists, and that's my fault. Thanks for the question!
